import { ColorType } from "@/types";

type ColorHandlerType = {
  color: ColorType;
};

export const colorHandler = ({ color }: ColorHandlerType) =>
  color === "alert-error-base"
    ? "alertErrorBase"
    : color === "alert-error-dark"
    ? "alertErrorDark"
    : color === "alert-error-light"
    ? "alertErrorLight"
    : color === "alert-success-base"
    ? "alertSuccessBase"
    : color === "alert-success-dark"
    ? "alertSuccessDark"
    : color === "alert-success-light"
    ? "alertSuccessLight"
    : color === "alert-warning-base"
    ? "alertWarningBase"
    : color === "alert-warning-dark"
    ? "alertWarningDark"
    : color === "alert-warning-light"
    ? "alertWarningLight"
    : color === "blue"
    ? "blue"
    : color === "orange"
    ? "orange"
    : color === "primary-100"
    ? "primary100"
    : color === "primary-200"
    ? "primary200"
    : color === "primary-300"
    ? "primary300"
    : color === "primary-400"
    ? "primary400"
    : color === "primary-base"
    ? "primaryBase"
    : color === "purple"
    ? "purple"
    : color === "white"
    ? "white"
    : color === "secondary-100"
    ? "secondary100"
    : color === "secondary-200"
    ? "secondary200"
    : color === "secondary-300"
    ? "secondary300"
    : color === "secondary-400"
    ? "secondary400"
    : color === "secondary-base"
    ? "secondaryBase"
    : color === "greyscale-50"
    ? "greyscale50"
    : color === "greyscale-100"
    ? "greyscale100"
    : color === "greyscale-200"
    ? "greyscale200"
    : color === "greyscale-300"
    ? "greyscale300"
    : color === "greyscale-400"
    ? "greyscale400"
    : color === "greyscale-500"
    ? "greyscale500"
    : color === "greyscale-600"
    ? "greyscale600"
    : color === "greyscale-700"
    ? "greyscale700"
    : color === "greyscale-800"
    ? "greyscale800"
    : "greyscale900";
